In [1]:
import os
import pandas as pd
import numpy as np

print("LankaLandslide AI")
print("Cleaning and merging data...")

LankaLandslide AI
Cleaning and merging data...

In [2]:
BASE_DIR = os.path.abspath("..")

LANDSLIDE_FILE = os.path.join(
    BASE_DIR,
    "data",
    "processed",
    "landslides_sri_lanka.csv"
)

WEATHER_FILE = os.path.join(
    BASE_DIR,
    "data",
    "raw",
    "weather",
    "sri_lanka_complete_daily_weather_1998_2025.csv"
)

OUTPUT_DIR = os.path.join(
    BASE_DIR,
    "data",
    "processed"
)

os.makedirs(OUTPUT_DIR, exist_ok=True)

MASTER_FILE = os.path.join(
    OUTPUT_DIR,
    "landslide_weather_master.csv"
)

print("Landslide file:")
print(LANDSLIDE_FILE)

print("\nWeather file:")
print(WEATHER_FILE)

print("\nMaster dataset:")
print(MASTER_FILE)

Landslide file:
c:\Users\User\Documents\GitHub\LankaLandslide-AI\data\processed\landslides_sri_lanka.csv

Weather file:
c:\Users\User\Documents\GitHub\LankaLandslide-AI\data\raw\weather\sri_lanka_complete_daily_weather_1998_2025.csv

Master dataset:
c:\Users\User\Documents\GitHub\LankaLandslide-AI\data\processed\landslide_weather_master.csv

Load landslide data

In [3]:
landslides = pd.read_csv(
    LANDSLIDE_FILE,
    parse_dates=["date"]
)

print("Landslide dataset loaded.")
print("Rows:", len(landslides))
print("Columns:", len(landslides.columns))

landslides.head()

Landslide dataset loaded.
Rows: 2256
Columns: 29

,record_number,serial,province,district,division,location,year,month,day,deaths,...,hospital_damage,school_damage,road_damage_km,duration,latitude,longitude,source,uuid,comments,date
0,1992,LA1974,Central,Nuwara Eliya,Ambagamuwakorale,Dicoya(GN),1974,7,27,9,...,0,0,0,0,0.0,0.0,DI19740729,d3dd2c5b-6ec4-11ea-b28b-005056ab3796,20081202,1974-07-27
1,2109,LA1974,Central,Nuwara Eliya,Ambagamuwakorale,Maskeliya(GN),1974,7,27,0,...,0,0,0,0,0.0,0.0,DI19740729,d3fa542a-6ec4-11ea-b28b-005056ab3796,20081202,1974-07-27
2,2110,LA1974,Central,Nuwara Eliya,Ambagamuwakorale,Hatton(GN),1974,7,27,0,...,0,0,0,0,0.0,0.0,DI19740729,d3fa5d5e-6ec4-11ea-b28b-005056ab3796,20081202,1974-07-27
3,1994,LA1974,Central,Nuwara Eliya,Kothmale,Pundaluoya(GN),1974,7,27,7,...,0,0,0,0,0.0,0.0,DI19740729P01,d3dd4510-6ec4-11ea-b28b-005056ab3796,20081202,1974-07-27
4,1993,LA1974,Central,Nuwara Eliya,Nuwara Eliya,"Dimbula(GN),Devon(GN)",1974,7,27,26,...,0,0,0,0,0.0,0.0,DI19740729P01,d3dd3928-6ec4-11ea-b28b-005056ab3796,20081202,1974-07-27

Load weather data

In [4]:
weather = pd.read_csv(
    WEATHER_FILE,
    parse_dates=["date"]
)

print("Weather dataset loaded.")
print("Rows:", len(weather))
print("Columns:", len(weather.columns))

weather.head()

Weather dataset loaded.
Rows: 245448
Columns: 12

,date,rainfall_mm,rain_mm,rain_hours,temp_max,temp_min,temp_mean,wind_max,wind_gust_max,district,latitude,longitude
0,1998-01-01,18.0,18.0,21.0,27.2,23.5,24.9,12.0,29.9,Ampara,7.2917,81.672
1,1998-01-02,8.4,8.4,15.0,27.8,23.6,25.4,22.2,45.4,Ampara,7.2917,81.672
2,1998-01-03,20.9,20.9,24.0,26.1,23.6,24.6,14.8,28.4,Ampara,7.2917,81.672
3,1998-01-04,11.0,11.0,17.0,26.1,23.5,25.1,15.3,31.3,Ampara,7.2917,81.672
4,1998-01-05,0.7,0.7,3.0,28.2,24.6,26.1,17.8,36.4,Ampara,7.2917,81.672

Inspect both datasets

In [5]:
print("LANDSLIDE DATA")
print("================")
print(landslides.info())

print("\n\nWEATHER DATA")
print("================")
print(weather.info())

LANDSLIDE DATA
================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2256 entries, 0 to 2255
Data columns (total 29 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   record_number       2256 non-null   int64
 1   serial              2256 non-null   object
 2   province            2256 non-null   object
 3   district            2256 non-null   object
 4   division            2250 non-null   object
 5   location            1941 non-null   object
 6   year                2256 non-null   int64
 7   month               2256 non-null   int64
 8   day                 2256 non-null   int64
 9   deaths              2256 non-null   int64
 10  injured             2256 non-null   int64
 11  missing             2256 non-null   int64
 12  affected_people     2256 non-null   int64
 13  houses_destroyed    2256 non-null   int64
 14  houses_affected     2256 non-null   int64
 15  cause               868 non-null    object
 16  agriculture_damage  2256 non-null   int64
 17  industry_damage     2256 non-null   int64
 18  transport_damage    2256 non-null   int64
 19  hospital_damage     2256 non-null   int64
 20  school_damage       2256 non-null   int64
 21  road_damage_km      2256 non-null   int64
 22  duration            2256 non-null   int64
 23  latitude            2256 non-null   float64
 24  longitude           2256 non-null   float64
 25  source              2239 non-null   object
 26  uuid                2256 non-null   object
 27  comments            2055 non-null   object
 28  date                2256 non-null   datetime64[ns]
dtypes: datetime64[ns](1), float64(2), int64(17), object(9)
memory usage: 511.3+ KB
None


WEATHER DATA
================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 245448 entries, 0 to 245447
Data columns (total 12 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   date           245448 non-null  datetime64[ns]
 1   rainfall_mm    245448 non-null  float64
 2   rain_mm        245448 non-null  float64
 3   rain_hours     245448 non-null  float64
 4   temp_max       245448 non-null  float64
 5   temp_min       245448 non-null  float64
 6   temp_mean      245448 non-null  float64
 7   wind_max       245448 non-null  float64
 8   wind_gust_max  245448 non-null  float64
 9   district       245448 non-null  object
 10  latitude       245448 non-null  float64
 11  longitude      245448 non-null  float64
dtypes: datetime64[ns](1), float64(10), object(1)
memory usage: 22.5+ MB
None

Standardize district names

In [6]:
landslides["district"] = (
    landslides["district"]
    .astype(str)
    .str.strip()
)

weather["district"] = (
    weather["district"]
    .astype(str)
    .str.strip()
)

print("Landslide districts:")
print(sorted(landslides["district"].unique()))

print("\nWeather districts:")
print(sorted(weather["district"].unique()))

Landslide districts:
['Badulla', 'Colombo', 'Galle', 'Gampaha', 'Hambantota', 'Kalutara', 'Kandy', 'Kegalle', 'Kurunegala', 'Matale', 'Matara', 'Moneragala', 'Nuwara Eliya', 'Polonnaruwa', 'Ratnapura']

Weather districts:
['Ampara', 'Anuradhapura', 'Badulla', 'Batticaloa', 'Colombo', 'Galle', 'Gampaha', 'Hambantota', 'Jaffna', 'Kalutara', 'Kandy', 'Kegalle', 'Kilinochchi', 'Kurunegala', 'Mannar', 'Matale', 'Matara', 'Monaragala', 'Nuwara Eliya', 'Polonnaruwa', 'Puttalam', 'Ratnapura', 'Trincomalee', 'Vavuniya']

Check district matching

In [7]:
landslide_districts = set(
    landslides["district"].dropna().unique()
)

weather_districts = set(
    weather["district"].dropna().unique()
)

print("Districts in both datasets:")
print(sorted(
    landslide_districts.intersection(weather_districts)
))

print("\nLandslide districts missing from weather:")
print(sorted(
    landslide_districts - weather_districts
))

print("\nWeather districts without landslide records:")
print(sorted(
    weather_districts - landslide_districts
))

Districts in both datasets:
['Badulla', 'Colombo', 'Galle', 'Gampaha', 'Hambantota', 'Kalutara', 'Kandy', 'Kegalle', 'Kurunegala', 'Matale', 'Matara', 'Nuwara Eliya', 'Polonnaruwa', 'Ratnapura']

Landslide districts missing from weather:
['Moneragala']

Weather districts without landslide records:
['Ampara', 'Anuradhapura', 'Batticaloa', 'Jaffna', 'Kilinochchi', 'Mannar', 'Monaragala', 'Puttalam', 'Trincomalee', 'Vavuniya']

Make sure dates are correct

In [8]:
landslides["date"] = pd.to_datetime(
    landslides["date"],
    errors="coerce"
)

weather["date"] = pd.to_datetime(
    weather["date"],
    errors="coerce"
)

print("Landslide date range:")
print(
    landslides["date"].min(),
    "→",
    landslides["date"].max()
)

print("\nWeather date range:")
print(
    weather["date"].min(),
    "→",
    weather["date"].max()
)

Landslide date range:
1974-07-27 00:00:00 → 2019-12-31 00:00:00

Weather date range:
1998-01-01 00:00:00 → 2025-12-31 00:00:00

Remove unusable landslide records

In [9]:
before = len(landslides)

landslides = landslides.dropna(
    subset=["date", "district"]
).copy()

after = len(landslides)

print("Records before:", before)
print("Records after:", after)
print("Removed:", before - after)

Records before: 2256
Records after: 2256
Removed: 0

reate daily landslide indicator

In [10]:
landslide_daily = (
    landslides
    .groupby(["district", "date"])
    .size()
    .reset_index(name="landslide_events")
)

landslide_daily["landslide_recorded"] = 1

print("Unique district-date landslide records:")
print(len(landslide_daily))

landslide_daily.head()

Unique district-date landslide records:
998

  district       date  landslide_events  landslide_recorded
0  Badulla 1975-04-20                 1                   1
1  Badulla 1979-01-20                 1                   1
2  Badulla 1984-03-06                 1                   1
3  Badulla 1985-12-15                 1                   1
4  Badulla 1986-01-04                 1                   1

Check multiple events

In [11]:
print(
    "District-date combinations with multiple landslide records:"
)

print(
    (landslide_daily["landslide_events"] > 1).sum()
)

District-date combinations with multiple landslide records:
292

Restrict training period

In [12]:
print(
    landslides["date"]
    .dt.year
    .value_counts()
    .sort_index()
)

date
1974      7
1975      2
1976      1
1977      1
1978     15
1979      1
1981      1
1982      8
1983      3
1984     10
1985      9
1986     43
1987      5
1988      3
1989     45
1990      4
1991      8
1992      9
1993     20
1994      3
1995     11
1996      6
1997     28
1998      6
1999     12
2000      4
2001      2
2002     20
2003    103
2004     36
2005     60
2006    777
2007    326
2008    220
2009    136
2010     82
2011     21
2012     14
2013     28
2014     39
2015     35
2016     20
2017     14
2018     20
2019     38
Name: count, dtype: int64

In [14]:
TRAIN_START = landslides["date"].min()
TRAIN_END = landslides["date"].max()

print("Training period:")
print(TRAIN_START, "→", TRAIN_END)

Training period:
1974-07-27 00:00:00 → 2019-12-31 00:00:00

Filter weather to the overlapping period

In [15]:
weather_train = weather[
    (weather["date"] >= TRAIN_START) &
    (weather["date"] <= TRAIN_END)
].copy()

print("Weather rows for training period:")
print(len(weather_train))

print(
    "Date range:",
    weather_train["date"].min(),
    "→",
    weather_train["date"].max()
)

Weather rows for training period:
192840
Date range: 1998-01-01 00:00:00 → 2019-12-31 00:00:00

Merge landslide records with weather

In [16]:
master = weather_train.merge(
    landslide_daily[
        [
            "district",
            "date",
            "landslide_events",
            "landslide_recorded"
        ]
    ],
    on=["district", "date"],
    how="left"
)

Create the target variable

In [17]:
master["landslide_events"] = (
    master["landslide_events"]
    .fillna(0)
    .astype(int)
)

master["landslide_recorded"] = (
    master["landslide_recorded"]
    .fillna(0)
    .astype(int)
)

print(
    master["landslide_recorded"]
    .value_counts()
)

landslide_recorded
0    191996
1       844
Name: count, dtype: int64

Check the master dataset

In [18]:
print("========================================")
print("MASTER DATASET")
print("========================================")

print("Rows:", len(master))
print("Columns:", len(master.columns))

print("\nDate range:")
print(
    master["date"].min(),
    "→",
    master["date"].max()
)

print("\nDistricts:")
print(master["district"].nunique())

print("\nTarget distribution:")
print(
    master["landslide_recorded"]
    .value_counts()
)

print("\nMissing values:")
print(
    master.isna().sum()
)

========================================
MASTER DATASET
========================================
Rows: 192840
Columns: 14

Date range:
1998-01-01 00:00:00 → 2019-12-31 00:00:00

Districts:
24

Target distribution:
landslide_recorded
0    191996
1       844
Name: count, dtype: int64

Missing values:
date                  0
rainfall_mm           0
rain_mm               0
rain_hours            0
temp_max              0
temp_min              0
temp_mean             0
wind_max              0
wind_gust_max         0
district              0
latitude              0
longitude             0
landslide_events      0
landslide_recorded    0
dtype: int64

Check duplicates

In [19]:
duplicates = master.duplicated(
    subset=["district", "date"]
).sum()

print(
    "Duplicate district-date rows:",
    duplicates
)

Duplicate district-date rows: 0

Missing values — inspect first

In [20]:
print("LANDSLIDE MISSING VALUES")
print("========================")
print(landslides.isna().sum())

print("\nWEATHER MISSING VALUES")
print("======================")
print(weather.isna().sum())

LANDSLIDE MISSING VALUES
========================
record_number            0
serial                   0
province                 0
district                 0
division                 6
location               315
year                     0
month                    0
day                      0
deaths                   0
injured                  0
missing                  0
affected_people          0
houses_destroyed         0
houses_affected          0
cause                 1388
agriculture_damage       0
industry_damage          0
transport_damage         0
hospital_damage          0
school_damage            0
road_damage_km           0
duration                 0
latitude                 0
longitude                0
source                  17
uuid                     0
comments               201
date                     0
dtype: int64

WEATHER MISSING VALUES
======================
date             0
rainfall_mm      0
rain_mm          0
rain_hours       0
temp_max         0
temp_min         0
temp_mean        0
wind_max         0
wind_gust_max    0
district         0
latitude         0
longitude        0
dtype: int64

In [21]:
# ============================================================
# COMPLETE MISSING VALUE REPORT
# ============================================================

landslide_missing = pd.DataFrame({
    "missing_count": landslides.isna().sum(),
    "missing_percent": (landslides.isna().mean() * 100).round(2)
})

landslide_missing = landslide_missing[
    landslide_missing["missing_count"] > 0
].sort_values("missing_count", ascending=False)

print("LANDSLIDE MISSING VALUES")
print("=" * 60)
print(landslide_missing.to_string())

LANDSLIDE MISSING VALUES
============================================================
          missing_count  missing_percent
cause              1388            61.52
location            315            13.96
comments            201             8.91
source               17             0.75
division              6             0.27

Check whether latitude/longitude are actually useful

In [22]:
# ============================================================
# CHECK INVALID COORDINATES
# ============================================================

invalid_coordinates = landslides[
    (landslides["latitude"] == 0) |
    (landslides["longitude"] == 0)
]

print("Records with 0 latitude/longitude:")
print(len(invalid_coordinates))

print("\nPercentage:")
print(round(len(invalid_coordinates) / len(landslides) * 100, 2), "%")

Records with 0 latitude/longitude:
2251

Percentage:
99.78 %

In [23]:
# ============================================================
# WEATHER MISSING VALUES
# ============================================================

weather_missing = pd.DataFrame({
    "missing_count": weather.isna().sum(),
    "missing_percent": (weather.isna().mean() * 100).round(2)
})

weather_missing = weather_missing[
    weather_missing["missing_count"] > 0
].sort_values("missing_count", ascending=False)

print("WEATHER MISSING VALUES")
print("=" * 60)
print(weather_missing.to_string())

WEATHER MISSING VALUES
============================================================
Empty DataFrame
Columns: [missing_count, missing_percent]
Index: []

In [24]:
def missing_report(df, name):

    report = pd.DataFrame({
        "missing_count": df.isna().sum(),
        "missing_percent": (
            df.isna().mean() * 100
        ).round(2)
    })

    print(f"\n{name}")
    print("=" * 50)
    print(report.sort_values(
        "missing_percent",
        ascending=False
    ))

missing_report(landslides, "LANDSLIDE DATA")
missing_report(weather, "WEATHER DATA")

LANDSLIDE DATA
==================================================
                    missing_count  missing_percent
cause                        1388            61.52
location                      315            13.96
comments                      201             8.91
source                         17             0.75
division                        6             0.27
district                        0             0.00
year                            0             0.00
month                           0             0.00
day                             0             0.00
deaths                          0             0.00
record_number                   0             0.00
province                        0             0.00
serial                          0             0.00
affected_people                 0             0.00
missing                         0             0.00
injured                         0             0.00
houses_destroyed                0             0.00
industry_damage                 0             0.00
transport_damage                0             0.00
houses_affected                 0             0.00
agriculture_damage              0             0.00
school_damage                   0             0.00
hospital_damage                 0             0.00
road_damage_km                  0             0.00
duration                        0             0.00
longitude                       0             0.00
latitude                        0             0.00
uuid                            0             0.00
date                            0             0.00

WEATHER DATA
==================================================
               missing_count  missing_percent
date                       0              0.0
rainfall_mm                0              0.0
rain_mm                    0              0.0
rain_hours                 0              0.0
temp_max                   0              0.0
temp_min                   0              0.0
temp_mean                  0              0.0
wind_max                   0              0.0
wind_gust_max              0              0.0
district                   0              0.0
latitude                   0              0.0
longitude                  0              0.0

Weather missing values

In [25]:
weather_missing = weather[
    weather.isna().any(axis=1)
]

print("Weather rows with missing values:")
print(len(weather_missing))

weather_missing.head()

Weather rows with missing values:
0

Empty DataFrame
Columns: [date, rainfall_mm, rain_mm, rain_hours, temp_max, temp_min, temp_mean, wind_max, wind_gust_max, district, latitude, longitude]
Index: []

Check invalid numerical values

In [26]:
print("Rainfall below zero:")
print((weather["rainfall_mm"] < 0).sum())

print("Temperature impossible values:")
print(
    (
        (weather["temp_min"] < -20) |
        (weather["temp_min"] > 60)
    ).sum()
)

print("Wind below zero:")
print((weather["wind_max"] < 0).sum())

Rainfall below zero:
0
Temperature impossible values:
0
Wind below zero:
0

Detect rainfall outliers using IQR

In [27]:
Q1 = weather["rainfall_mm"].quantile(0.25)
Q3 = weather["rainfall_mm"].quantile(0.75)

IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

rainfall_outliers = weather[
    (weather["rainfall_mm"] < lower_bound) |
    (weather["rainfall_mm"] > upper_bound)
]

print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)

print("\nLower bound:", lower_bound)
print("Upper bound:", upper_bound)

print("\nPotential rainfall outliers:")
print(len(rainfall_outliers))

Q1: 0.1
Q3: 6.2
IQR: 6.1000000000000005

Lower bound: -9.05
Upper bound: 15.350000000000001

Potential rainfall outliers:
22230

Inspect the largest rainfall values

In [28]:
weather[
    [
        "date",
        "district",
        "rainfall_mm"
    ]
].sort_values(
    "rainfall_mm",
    ascending=False
).head(20)

             date    district  rainfall_mm
224188 2023-10-18   Ratnapura        265.0
119206 2016-05-15     Kegalle        259.5
122690 2025-11-28     Kegalle        259.1
90190  2020-12-05      Jaffna        255.8
139660 2016-05-15  Kurunegala        254.0
162826 2023-10-18      Matale        246.8
108467 2014-12-20       Kandy        236.8
2880   2005-11-20      Ampara        235.0
211250 2016-05-16    Puttalam        233.6
160114 2016-05-15      Matale        233.3
220899 2014-10-16   Ratnapura        232.9
68071  2016-05-15     Gampaha        231.4
47617  2016-05-15     Colombo        231.4
139661 2016-05-16  Kurunegala        227.5
28068  2018-11-06     Badulla        224.2
107026 2011-01-09       Kandy        220.4
112462 2025-11-27       Kandy        217.6
160115 2016-05-16      Matale        217.4
71555  2025-11-28     Gampaha        213.9
51101  2025-11-28     Colombo        213.9

Check weather outliers

In [29]:
def iqr_report(df, column):

    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)

    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    outliers = df[
        (df[column] < lower) |
        (df[column] > upper)
    ]

    print(f"\n{column}")
    print("-" * 40)
    print("Q1:", Q1)
    print("Q3:", Q3)
    print("IQR:", IQR)
    print("Lower:", lower)
    print("Upper:", upper)
    print("Potential outliers:", len(outliers))


iqr_report(weather, "rainfall_mm")
iqr_report(weather, "temp_max")
iqr_report(weather, "temp_min")
iqr_report(weather, "wind_max")
iqr_report(weather, "wind_gust_max")

rainfall_mm
----------------------------------------
Q1: 0.1
Q3: 6.2
IQR: 6.1000000000000005
Lower: -9.05
Upper: 15.350000000000001
Potential outliers: 22230

temp_max
----------------------------------------
Q1: 28.8
Q3: 32.0
IQR: 3.1999999999999993
Lower: 24.0
Upper: 36.8
Potential outliers: 12380

temp_min
----------------------------------------
Q1: 22.9
Q3: 25.6
IQR: 2.700000000000003
Lower: 18.849999999999994
Upper: 29.650000000000006
Potential outliers: 13048

wind_max
----------------------------------------
Q1: 10.6
Q3: 20.3
IQR: 9.700000000000001
Lower: -3.950000000000001
Upper: 34.85
Potential outliers: 3464

wind_gust_max
----------------------------------------
Q1: 27.4
Q3: 43.6
IQR: 16.200000000000003
Lower: 3.0999999999999943
Upper: 67.9
Potential outliers: 1893

Create the target variable

In [30]:
master["landslide_events"] = (
    master["landslide_events"]
    .fillna(0)
    .astype(int)
)

master["landslide_recorded"] = (
    master["landslide_recorded"]
    .fillna(0)
    .astype(int)
)

print(
    master["landslide_recorded"]
    .value_counts()
)

landslide_recorded
0    191996
1       844
Name: count, dtype: int64

Check the master dataset

In [31]:
print("========================================")
print("MASTER DATASET")
print("========================================")

print("Rows:", len(master))
print("Columns:", len(master.columns))

print("\nDate range:")
print(
    master["date"].min(),
    "→",
    master["date"].max()
)

print("\nDistricts:")
print(master["district"].nunique())

print("\nTarget distribution:")
print(
    master["landslide_recorded"]
    .value_counts()
)

print("\nMissing values:")
print(
    master.isna().sum()
)

========================================
MASTER DATASET
========================================
Rows: 192840
Columns: 14

Date range:
1998-01-01 00:00:00 → 2019-12-31 00:00:00

Districts:
24

Target distribution:
landslide_recorded
0    191996
1       844
Name: count, dtype: int64

Missing values:
date                  0
rainfall_mm           0
rain_mm               0
rain_hours            0
temp_max              0
temp_min              0
temp_mean             0
wind_max              0
wind_gust_max         0
district              0
latitude              0
longitude             0
landslide_events      0
landslide_recorded    0
dtype: int64

Save the master dataset

In [32]:
master = master.sort_values(
    ["district", "date"]
).reset_index(drop=True)

master.to_csv(
    MASTER_FILE,
    index=False
)

print("========================================")
print("MASTER DATASET SAVED")
print("========================================")

print(MASTER_FILE)
print("Rows:", len(master))
print("Columns:", len(master.columns))

========================================
MASTER DATASET SAVED
========================================
c:\Users\User\Documents\GitHub\LankaLandslide-AI\data\processed\landslide_weather_master.csv
Rows: 192840
Columns: 14

Final preview

In [33]:
master.head(20)

,date,rainfall_mm,rain_mm,rain_hours,temp_max,temp_min,temp_mean,wind_max,wind_gust_max,district,latitude,longitude,landslide_events,landslide_recorded
0,1998-01-01,18.0,18.0,21.0,27.2,23.5,24.9,12.0,29.9,Ampara,7.2917,81.672,0,0
1,1998-01-02,8.4,8.4,15.0,27.8,23.6,25.4,22.2,45.4,Ampara,7.2917,81.672,0,0
2,1998-01-03,20.9,20.9,24.0,26.1,23.6,24.6,14.8,28.4,Ampara,7.2917,81.672,0,0
3,1998-01-04,11.0,11.0,17.0,26.1,23.5,25.1,15.3,31.3,Ampara,7.2917,81.672,0,0
4,1998-01-05,0.7,0.7,3.0,28.2,24.6,26.1,17.8,36.4,Ampara,7.2917,81.672,0,0
5,1998-01-06,1.9,1.9,9.0,28.7,24.4,26.3,22.4,45.7,Ampara,7.2917,81.672,0,0
6,1998-01-07,2.9,2.9,9.0,27.8,23.6,25.3,20.0,41.4,Ampara,7.2917,81.672,0,0
7,1998-01-08,4.1,4.1,15.0,27.9,23.7,25.4,16.7,36.7,Ampara,7.2917,81.672,0,0
8,1998-01-09,4.3,4.3,17.0,27.9,24.5,25.7,14.7,33.1,Ampara,7.2917,81.672,0,0
9,1998-01-10,2.7,2.7,15.0,28.5,24.5,26.2,20.2,41.0,Ampara,7.2917,81.672,0,0
10,1998-01-11,0.1,0.1,1.0,27.8,24.5,25.8,22.2,45.4,Ampara,7.2917,81.672,0,0
11,1998-01-12,2.0,2.0,12.0,27.6,24.5,26.0,23.8,48.6,Ampara,7.2917,81.672,0,0
12,1998-01-13,0.3,0.3,2.0,29.3,24.3,26.3,19.7,39.6,Ampara,7.2917,81.672,0,0
13,1998-01-14,0.0,0.0,0.0,28.9,23.9,26.0,17.0,35.3,Ampara,7.2917,81.672,0,0
14,1998-01-15,0.0,0.0,0.0,28.8,22.6,25.2,17.2,33.5,Ampara,7.2917,81.672,0,0
15,1998-01-16,0.0,0.0,0.0,27.7,21.5,24.2,12.6,28.8,Ampara,7.2917,81.672,0,0
16,1998-01-17,0.0,0.0,0.0,28.3,22.9,25.7,12.8,28.1,Ampara,7.2917,81.672,0,0
17,1998-01-18,0.2,0.2,1.0,29.4,23.9,26.4,10.3,23.8,Ampara,7.2917,81.672,0,0
18,1998-01-19,1.0,1.0,6.0,29.3,24.2,26.5,14.3,29.2,Ampara,7.2917,81.672,0,0
19,1998-01-20,0.1,0.1,1.0,29.1,23.4,25.8,12.6,29.9,Ampara,7.2917,81.672,0,0

In [34]:
master.tail(20)

,date,rainfall_mm,rain_mm,rain_hours,temp_max,temp_min,temp_mean,wind_max,wind_gust_max,district,latitude,longitude,landslide_events,landslide_recorded
192820,2019-12-12,1.8,1.8,4.0,28.4,22.8,25.3,12.2,32.4,Vavuniya,8.7514,80.4971,0,0
192821,2019-12-13,7.0,7.0,8.0,29.1,23.1,25.8,13.7,32.8,Vavuniya,8.7514,80.4971,0,0
192822,2019-12-14,1.4,1.4,7.0,28.3,23.8,25.6,17.0,41.0,Vavuniya,8.7514,80.4971,0,0
192823,2019-12-15,1.0,1.0,5.0,29.4,23.3,25.6,16.4,35.3,Vavuniya,8.7514,80.4971,0,0
192824,2019-12-16,1.7,1.7,7.0,29.6,22.4,25.5,16.9,37.1,Vavuniya,8.7514,80.4971,0,0
192825,2019-12-17,3.0,3.0,13.0,28.7,23.8,25.7,17.4,40.7,Vavuniya,8.7514,80.4971,0,0
192826,2019-12-18,3.7,3.7,14.0,28.2,23.5,25.6,17.0,40.7,Vavuniya,8.7514,80.4971,0,0
192827,2019-12-19,2.6,2.6,13.0,27.8,24.0,25.8,20.3,42.8,Vavuniya,8.7514,80.4971,0,0
192828,2019-12-20,6.9,6.9,17.0,26.6,23.8,24.8,18.5,36.0,Vavuniya,8.7514,80.4971,0,0
192829,2019-12-21,2.2,2.2,10.0,29.0,23.5,25.7,17.6,42.1,Vavuniya,8.7514,80.4971,0,0
192830,2019-12-22,4.6,4.6,14.0,28.4,24.1,25.7,16.7,37.8,Vavuniya,8.7514,80.4971,0,0
192831,2019-12-23,54.8,54.8,12.0,27.5,23.5,25.1,12.1,26.6,Vavuniya,8.7514,80.4971,0,0
192832,2019-12-24,0.7,0.7,4.0,30.5,22.9,26.3,10.9,29.5,Vavuniya,8.7514,80.4971,0,0
192833,2019-12-25,1.6,1.6,5.0,28.5,23.5,25.4,13.5,32.4,Vavuniya,8.7514,80.4971,0,0
192834,2019-12-26,0.0,0.0,0.0,29.4,21.8,25.3,12.7,27.0,Vavuniya,8.7514,80.4971,0,0
192835,2019-12-27,0.0,0.0,0.0,30.1,20.5,25.0,12.1,24.1,Vavuniya,8.7514,80.4971,0,0
192836,2019-12-28,0.0,0.0,0.0,29.1,22.0,25.0,14.5,32.0,Vavuniya,8.7514,80.4971,0,0
192837,2019-12-29,0.0,0.0,0.0,29.9,21.6,25.4,17.3,36.7,Vavuniya,8.7514,80.4971,0,0
192838,2019-12-30,0.9,0.9,6.0,29.8,21.9,25.6,14.6,31.7,Vavuniya,8.7514,80.4971,0,0
192839,2019-12-31,1.6,1.6,6.0,29.3,22.4,25.6,13.2,30.2,Vavuniya,8.7514,80.4971,0,0

In [34]:
master.tail(20)

,date,rainfall_mm,rain_mm,rain_hours,temp_max,temp_min,temp_mean,wind_max,wind_gust_max,district,latitude,longitude,landslide_events,landslide_recorded
192820,2019-12-12,1.8,1.8,4.0,28.4,22.8,25.3,12.2,32.4,Vavuniya,8.7514,80.4971,0,0
192821,2019-12-13,7.0,7.0,8.0,29.1,23.1,25.8,13.7,32.8,Vavuniya,8.7514,80.4971,0,0
192822,2019-12-14,1.4,1.4,7.0,28.3,23.8,25.6,17.0,41.0,Vavuniya,8.7514,80.4971,0,0
192823,2019-12-15,1.0,1.0,5.0,29.4,23.3,25.6,16.4,35.3,Vavuniya,8.7514,80.4971,0,0
192824,2019-12-16,1.7,1.7,7.0,29.6,22.4,25.5,16.9,37.1,Vavuniya,8.7514,80.4971,0,0
192825,2019-12-17,3.0,3.0,13.0,28.7,23.8,25.7,17.4,40.7,Vavuniya,8.7514,80.4971,0,0
192826,2019-12-18,3.7,3.7,14.0,28.2,23.5,25.6,17.0,40.7,Vavuniya,8.7514,80.4971,0,0
192827,2019-12-19,2.6,2.6,13.0,27.8,24.0,25.8,20.3,42.8,Vavuniya,8.7514,80.4971,0,0
192828,2019-12-20,6.9,6.9,17.0,26.6,23.8,24.8,18.5,36.0,Vavuniya,8.7514,80.4971,0,0
192829,2019-12-21,2.2,2.2,10.0,29.0,23.5,25.7,17.6,42.1,Vavuniya,8.7514,80.4971,0,0
192830,2019-12-22,4.6,4.6,14.0,28.4,24.1,25.7,16.7,37.8,Vavuniya,8.7514,80.4971,0,0
192831,2019-12-23,54.8,54.8,12.0,27.5,23.5,25.1,12.1,26.6,Vavuniya,8.7514,80.4971,0,0
192832,2019-12-24,0.7,0.7,4.0,30.5,22.9,26.3,10.9,29.5,Vavuniya,8.7514,80.4971,0,0
192833,2019-12-25,1.6,1.6,5.0,28.5,23.5,25.4,13.5,32.4,Vavuniya,8.7514,80.4971,0,0
192834,2019-12-26,0.0,0.0,0.0,29.4,21.8,25.3,12.7,27.0,Vavuniya,8.7514,80.4971,0,0
192835,2019-12-27,0.0,0.0,0.0,30.1,20.5,25.0,12.1,24.1,Vavuniya,8.7514,80.4971,0,0
192836,2019-12-28,0.0,0.0,0.0,29.1,22.0,25.0,14.5,32.0,Vavuniya,8.7514,80.4971,0,0
192837,2019-12-29,0.0,0.0,0.0,29.9,21.6,25.4,17.3,36.7,Vavuniya,8.7514,80.4971,0,0
192838,2019-12-30,0.9,0.9,6.0,29.8,21.9,25.6,14.6,31.7,Vavuniya,8.7514,80.4971,0,0
192839,2019-12-31,1.6,1.6,6.0,29.3,22.4,25.6,13.2,30.2,Vavuniya,8.7514,80.4971,0,0

In [35]:
# ============================================================
# MASTER DATASET VALIDATION
# ============================================================

print("MASTER DATASET VALIDATION")
print("=" * 60)

print("Rows:", len(master))
print("Columns:", len(master.columns))

print("\nDate range:")
print(master["date"].min(), "→", master["date"].max())

print("\nNumber of districts:")
print(master["district"].nunique())

print("\nDistricts:")
print(sorted(master["district"].unique()))

MASTER DATASET VALIDATION
============================================================
Rows: 192840
Columns: 14

Date range:
1998-01-01 00:00:00 → 2019-12-31 00:00:00

Number of districts:
24

Districts:
['Ampara', 'Anuradhapura', 'Badulla', 'Batticaloa', 'Colombo', 'Galle', 'Gampaha', 'Hambantota', 'Jaffna', 'Kalutara', 'Kandy', 'Kegalle', 'Kilinochchi', 'Kurunegala', 'Mannar', 'Matale', 'Matara', 'Monaragala', 'Nuwara Eliya', 'Polonnaruwa', 'Puttalam', 'Ratnapura', 'Trincomalee', 'Vavuniya']

In [36]:
# ============================================================
# 1. DUPLICATE CHECK
# ============================================================

duplicates = master.duplicated(subset=["district", "date"]).sum()

print("Duplicate district-date combinations:", duplicates)

Duplicate district-date combinations: 0

In [37]:
# ============================================================
# 2. MISSING VALUES
# ============================================================

missing_report = pd.DataFrame({
    "missing_count": master.isna().sum(),
    "missing_percent": (master.isna().mean() * 100).round(2)
})

print(missing_report.to_string())

                    missing_count  missing_percent
date                            0              0.0
rainfall_mm                     0              0.0
rain_mm                         0              0.0
rain_hours                      0              0.0
temp_max                        0              0.0
temp_min                        0              0.0
temp_mean                       0              0.0
wind_max                        0              0.0
wind_gust_max                   0              0.0
district                        0              0.0
latitude                        0              0.0
longitude                       0              0.0
landslide_events                0              0.0
landslide_recorded              0              0.0

In [38]:
# ============================================================
# 3. INVALID VALUES
# ============================================================

print("Negative rainfall:", (master["rainfall_mm"] < 0).sum())
print("Negative rain:", (master["rain_mm"] < 0).sum())
print("Negative wind:", (master["wind_max"] < 0).sum())
print("Negative wind gust:", (master["wind_gust_max"] < 0).sum())

print(
    "Impossible temperature:",
    (
        (master["temp_min"] < -20) |
        (master["temp_min"] > 60) |
        (master["temp_max"] < -20) |
        (master["temp_max"] > 60)
    ).sum()
)

Negative rainfall: 0
Negative rain: 0
Negative wind: 0
Negative wind gust: 0
Impossible temperature: 0

In [39]:
# ============================================================
# 4. LANDSLIDE TARGET DISTRIBUTION
# ============================================================

print("Landslide recorded distribution:")
print(master["landslide_recorded"].value_counts())

print("\nPercentage:")
print(
    master["landslide_recorded"]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
)

Landslide recorded distribution:
landslide_recorded
0    191996
1       844
Name: count, dtype: int64

Percentage:
landslide_recorded
0    99.56
1     0.44
Name: proportion, dtype: float64